### ISSUE TITLE
poor result

### ISSUE THREAD

**Issue by charmway** [s-sd/task-amenability#1]
Hello, I have followed this work and got a poor result using the [PneumoniaMNIST dataset](https://medmnist.github.io/).
due to the absence of preprocessed files, I write my own preprocess algorithm. to keep the consistency in train/val/holdout, each of them has the same proportion of corrupted images(24/524). There are 4 types of corrupting in my algorithm:
1. fully corrupt(100%) with value 255
2. half corrupt(the top half) with value 255
3. randomly corrupt(50%) with value 255
4. randomly corrupt(1/28) with value 255

After doing that, I get the `npz` file. Ecerything else keeps the same. However the controller predict 1 for all samples in holdout dataset, while there are about 28 samples which are corrupted. it seems controller predicts poorly about the image quality.
By the way, my `npz` file is 4493 kb, but the file in your repo is 11684 kb.

**Comment by s-sd** [comment]
Hi Tom,

Thanks for your emails earlier and for creating this issue. The files used in the experiment along with a trained model are available under the pneumonia_mnist directory. This is the data used in the experiment for which we report the results. While I cannot comment on your dataset and corruption procedure, since I do not have the data available, from the description it does seem that your corruption strategy either makes the image very corrupt or does not corrupt it at all. On the images that are corrupted then the controller produces a score close to zero and one for the rest. This is expected for a dataset of this kind since not enough variety may be present. If you want the controller to learn more continuous values, I would recommend using a dataset where corruption varies more continuously rather than either being corrupted or not corrupted. For example the included corrupted data has number of pixels corruption percentage sampled from a distribution and applied to all images. 

I will add the code used to corrupt the images in a few days.

Hope that helps!

**Comment by s-sd** [comment]
Hi @Tom-Teamo! Please see the added file for data corruption (PR #2 - now merged to main), it has functions for corruption and also one example for how to create an example dataset. Hope that helps. :)

**Comment by charmway** [comment]
wow (0.0)
Thank you very much. I will see it later.
Hope you get better~
